#!/bin/bash

source ../../initialize_parameters.sh

#We store current path:
CURRENT_DIR=$PWD

echo -e "${ORANGE}Please, assure that you have a sample-manifest.tsv file prepared."
#Ask for run ID numbers
echo -e "${LIGHTCYAN}Now please, enter the numbers of run sequencings (ex: 1,2,3):"
    read runNums

#Convert seq numbers to vector
my_string=$runNums
my_array=($(echo $my_string | tr "," "\n"))

for runNums in "${my_array[@]}"
do
    echo -e "${PURPLE}Importing samples.."
    # Import samples to .qza for Qiime2
    qiime tools import \
    --type 'SampleData[SequencesWithQuality]' \
    --input-path ${CURRENT_DIR}/samples-manifest-run${runNums}.tsv \
    --input-format SingleEndFastqManifestPhred33V2 \
    --output-path ${CURRENT_DIR}/samples-run${runNums}.qza
done

# Perform Cutadapt
bash $DIR/src/IT_Cutadapt_Primers_different_seqRuns