#!/bin/bash

source ../../initialize_parameters.sh

# Store current path:
CURRENT_DIR=$PWD

echo -e "${ORANGE}Please, assure that you have a sample-manifest.tsv file prepared."

echo -e "${PURPLE}Importing samples..."
# Importing samples to Qiime2
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path ${CURRENT_DIR}/samples-manifest.tsv \
  --input-format SingleEndFastqManifestPhred33V2 \
  --output-path ${CURRENT_DIR}/samples.qza

# Perform Cutadapt
bash $DIR/src/IT_Cutadapt_Primers