#!/bin/bash

source ../../initialize_parameters.sh

# Store current path:
CURRENT_DIR=$PWD

echo -e "${ORANGE}Please, assure that you have a sample-manifest.tsv file prepared."

# Importing samples to Qiime2
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path ${CURRENT_DIR}/samples-manifest.tsv \
  --input-format SingleEndFastqManifestPhred33V2 \
  --output-path ${CURRENT_DIR}/samples.qza

qiime demux summarize \
  --i-data  ${CURRENT_DIR}/samples.qza \
  --o-visualization ${CURRENT_DIR}/samples-demux.qzv

# Perform Dada2
bash $DIR/src/IT_16Skit_Dada2


