#!/bin/bash

source ../../initialize_parameters.sh

#We store current path:
CURRENT_DIR=$PWD

# Visualize the quality graphs for decide the DADA2 parameters. 
echo -e "${ORANGE}Before DADA2 step, you need to visualize samples.qza (through samples.qzv) and decide the length of reads, 
so we can trunc by quality. Take a look to the graph that has been opened up."

echo -e "$ORANGE If you have previously decided to perform CUTADAPT because you knew the exact primer sequences,
 now you should choose a 0 (zero) in the trimming parameters. If not, you should select a trimming length that 
 removes the lower quality base pairs from the left of the quality graph."

# Visualize Quality graph
qiime tools view ${CURRENT_DIR}/samples.qzv

# Ask for truncating and trimming parameters:
echo -e "${LIGHTCYAN} Enter truncating length"
read trunc_lenVal
echo -e "${LIGHTCYAN} Enter trimming length"
read trim_lenVal

mkdir $CURRENT_DIR/Dada2_output

# DADA2 step
echo -e "${PURPLE}Performing Dada2...${NC}"
qiime dada2 denoise-pyro \
  --i-demultiplexed-seqs ${CURRENT_DIR}/samples.qza\
  --p-trunc-len ${trunc_lenVal} \
  --p-trim-left ${trim_lenVal} \
  --p-n-threads 4 \
  --o-representative-sequences ${CURRENT_DIR}/Dada2_output/rep-seqs-pyro.qza \
  --o-table ${CURRENT_DIR}/Dada2_output/table-pyro.qza \
  --o-denoising-stats ${CURRENT_DIR}/Dada2_output/stats-dada2-pyro.qza \
  --verbose

#Visualizing Resulting data...
#Converting DADA2 artifact .qza to .qzv
qiime feature-table summarize \
  --i-table ${CURRENT_DIR}/Dada2_output/table-pyro.qza \
  --o-visualization ${CURRENT_DIR}/Dada2_output/table-pyro.qzv \
  --m-sample-metadata-file ${CURRENT_DIR}/samples-metadata.tsv
qiime feature-table tabulate-seqs \
  --i-data ${CURRENT_DIR}/Dada2_output/rep-seqs-pyro.qza \
  --o-visualization ${CURRENT_DIR}/Dada2_output/rep-seqs-pyro.qzv
qiime metadata tabulate \
  --m-input-file ${CURRENT_DIR}/Dada2_output/stats-dada2-pyro.qza \
  --o-visualization ${CURRENT_DIR}/Dada2_output/stats-dada2-pyro.qzv

# Create report with the parameters used:
echo -e "${Purple} Creating summary report..."
echo "This is a summary report of the parameters used in DADA2 step: 
                        Truncating Length: ${trunc_lenVal}
                        Trimming Length: ${trim_lenVal}" >| ${CURRENT_DIR}/Dada2_output/DADA2_parameters_report.txt




# Ask if the DADA2 step needs to be repeated:
echo -e "${ORANGE}Sometimes the truncating length value we choose may not be optimal. To be able to assess whether we should choose another value, we must view the statistics table that is created after the Dada2 step. To know if the chosen value is good, we must look at the percentage of reads that pass the filter. For example, 70% would not be bad. However, we can re-run the Dada2 step with another value to compare the percentages. Let's visualize the statistic tables of each run run:"

# Visualize stats .qzv
qiime tools view ${CURRENT_DIR}/Dada2_output/stats-dada2-pyro.qzv

echo -e "${ORANGE}Once you have vizualize the statistic table... ${lightCyan} Do you want to re-run dada2? (Write Yes or No)"
read repeatDada2
   
if test ${repeatDada2} == "Yes"; then 
  echo -e "${PURPLE}Running DADA2 again..."
  bash $DIR/src/IT_Primers_Dada2

elif test ${repeatDada2} == "No"; then
  echo -e "${PURPLE}Going forward to Taxonomic Classification..."
  bash $DIR/src/TaxonomicClassification
fi



