#!/bin/bash

################___I wanted to use different colors in the terminal for different functions, so I need to initialize them (ref: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)

lightCyan='\033[1;36m'
RED='\033[0;31m'
Purple='\033[0;35m'
White='\033[1;37m'
NC='\033[0m' # No Color

#We need to know many thing before start:
echo -e "${White}Before we start... Give this analysis a experiment name: "
read AnalysysName

echo "Now, please answer the following questions:
1) Which sequencer did you perform the sequenciation step with?${lightCyan}(Write IonTorrent or Illumina):" 
read sequencer

echo -e "${White}2) Did you use the 16S Metagenomic Kit or other primers?${lightCyan}(Write Kit or Primers): " 
read kitPrimer

echo -e "${White}3) Do your samples come from different sequenciations (different PGM numbers)?${lightCyan}(Write Yes or No): " 
read difSequenciations


## Machine Learning:
echo -e "${White} Supervised Machine Learning is used for the prediction of a certain variable. ${lightCyan}Please, enter the name of the variable (metadata column) you would like to infer:"
read metadataCol_val

echo -e "${Purple} Applying Supervised Machine Learning...${NC} "

mkdir MachineLearning

qiime sample-classifier classify-samples \
  --i-table ${file_dir}/Dada2_output/table-dada2-pyro-conTrun${trunc_lenVal}.qza \
  --m-metadata-file ${file_dir}/samples-metadata.tsv \
  --m-metadata-column ${metadataCol_val} \
  --p-random-state 666 \
  --p-n-jobs 1 \
  --output-dir ${file_dir}/MachineLearning/sample-classifier-results-${metadataCol_val}/














