#!/bin/bash

source ../../initialize_parameters.sh

#We store current path:
CURRENT_DIR=$PWD

#Here write the path to your experiment:
#******************** CHANGE THE PATH OF THE EXPERIMENT **********************
EXPERIMENT_NAME=MicrobiomaCirculante

#******************** CHANGE THE PATHS AND FILE NAMES **********************
# remember to use single or paired for Illumina and pyro for Ion Torrent
#********************YOU NEED TO WRITE THIS ROW FOR EACH RUN YOU ARE ANALYZING:********************
#--i-data ${DIR}/Dada2_output/run1-rep-seqs-pyro.qza \
# or
#--i-data ${DIR}/Dada2_output/run1-rep-seqs-single.qza \
#--i-data ${DIR}/Dada2_output/run1-rep-seqs-paired.qza \

EXPERIMENT_DIR=$DIR/EXPERIMENTS/$EXPERIMENT_NAME

echo -e "${PURPLE}Merging dada2 tables of different runs..."

qiime feature-table merge-seqs \
  --i-data ${EXPERIMENT_DIR}/Dada2_output/run1-rep-seqs-pyro.qza \
  --i-data ${EXPERIMENT_DIR}/Dada2_output/run2-rep-seqs-pyro.qza \
  --i-data ${EXPERIMENT_DIR}/Dada2_output/run3-rep-seqs-pyro.qza \
  --o-merged-data ${EXPERIMENT_DIR}/Dada2_output/rep-seqs-pyro.qza

qiime feature-table tabulate-seqs \
  --i-data ${EXPERIMENT_DIR}/Dada2_output/rep-seqs-pyro.qza \
  --o-visualization ${EXPERIMENT_DIR}/Dada2_output/rep-seqs-pyro.qzv

#********************YOU NEED TO WRITE THIS ROW FOR EACH PGM YOU ARE ANALYZING: (Note now is not --i-data , but, i--tables)********************
#--i-tables ${DIR}/Dada2_output/run1-table-pyro.qza \
qiime feature-table merge \
  --i-tables ${EXPERIMENT_DIR}/Dada2_output/run1-table-pyro.qza \
  --i-tables ${EXPERIMENT_DIR}/Dada2_output/run2-table-pyro.qza \
  --i-tables ${EXPERIMENT_DIR}/Dada2_output/run3-table-pyro.qza \
  --o-merged-table ${EXPERIMENT_DIR}/Dada2_output/table-pyro.qza \
  --p-overlap-method sum

qiime feature-table summarize \
  --i-table ${EXPERIMENT_DIR}/Dada2_output/table-pyro.qza \
  --o-visualization ${EXPERIMENT_DIR}/Dada2_output/table-pyro.qzv \
  --m-sample-metadata-file ${EXPERIMENT_DIR}/samples-metadata.tsv

###################################
# Don't modify this:
echo -e "${ORANGE} Make sure the merged rep-seqs.qza and the table.qza files have been created. Now we will perform the Taxonomic analysis:"
# Perform Taxonomic Classification:
bash $DIR/src/TaxonomicClassification
