#!/bin/bash

source ../../initialize_parameters.sh

#We store current path:
CURRENT_DIR=$PWD
#CURRENT_DIR='/home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/mbiome/EXPERIMENTS/Prueba16S'

echo -e "${PURPLE}Running q2-metnet Functional Analysis...${NC}"
mkdir ${CURRENT_DIR}/Metnet

echo -e "${PURPLE} Installing metnet...${NC}"
# git clone https://github.com/PlanesLab/q2-metnet.git $DIR/q2-metnet
# cd $DIR/q2-metnet/q2_metnet/
# unzip data.zip
# rm data.zip
# cd ..
# python setup.py install
# qiime dev refresh-cache

# github: https://github.com/PlanesLab/q2-metnet

#Ask the approach to follow: AGREDA or AGORA:
echo -e "${ORANGE} Please select the approach to follow. ${LIGHTCYAN} Options (AGREDA, AGORAv103):"
read pipelineSelection

#Ask for the taxonomy level:
echo -e "${ORANGE} Please select the taxonomy level you want to analyze. ${LIGHTCYAN} Ranging from kingdom (k) to species (s):"
read taxLevel

#Ask for the metadata column and the name of the goups correspondign to condition or to control:
echo -e "${LIGHTCYAN} Please write the name of the metadata column that contains the groups:"
read metadataCol
echo -e "${LIGHTCYAN} Now the name of the group that refers to the "condition" or disease (ex: MS):"
read conditionGroup
echo -e "${LIGHTCYAN} Now the name of the group that refers to the "control" (ex: HC):"
read controlGroup

# Ask for exchange parameter:
echo -e "${ORANGE} It is necessary to decide if we want the focus of the differential analysis to be input (and may be output as well) or just output. ${LIGHTCYAN} Write down 'False' for the first option and 'True' for just output:"
read inputInterest

#Ask for sequencing type:
echo -e "${ORANGE} Please enter if the sequenciation has been IonTorrent (then write pyro) or if it has been through Illumina (write if it has been paired or single). ${LIGHTCYAN} Options (pyro, paired, single):"
read seqType

#pip install biom-format
# Export .qza files:
qiime tools export \
  --input-path ${CURRENT_DIR}/Dada2_output/table-${seqType}.qza \
  --output-path ${CURRENT_DIR}/exported-dada2table

biom convert \
  -i ${CURRENT_DIR}/exported-dada2table/feature-table.biom \
  -o ${CURRENT_DIR}/exported-dada2table/feature-table.tsv \
  --to-tsv


python3 $DIR/src/biom_transponse.py "$CURRENT_DIR"

# Continuar con comandos de Bash
echo "Convirtiendo de nuevo a .biom"
biom convert \
 -i ${CURRENT_DIR}/exported-dada2table/transposed-feature-table.tsv \
 -o ${CURRENT_DIR}/exported-dada2table/transposed-feature-table.biom --table-type="OTU table" --to-hdf5


qiime tools import \
  --type 'FeatureTable[Frequency]' \
  --input-format BIOMV210Format \
  --input-path ${CURRENT_DIR}/exported-dada2table/transposed-feature-table.biom  \
  --output-path ${CURRENT_DIR}/exported-dada2table/feature-table.qza


#Generate the normalized scores tables
qiime metnet generateFeatures \
	--i-frequency ${CURRENT_DIR}/exported-dada2table/feature-table.qza \
	--i-taxa ${CURRENT_DIR}/Taxonomic-Analysis/taxonomy-${seqType}-gg97-vsearch.qza \
	--p-selection ${pipelineSelection} \
	--p-level ${taxLevel} \
	--o-reactions ${CURRENT_DIR}/Metnet/output_reactions.qza \
	--o-subsystems ${CURRENT_DIR}/Metnet/output_subsystems.qza \
	--o-xmatrix ${CURRENT_DIR}/Metnet/output_X_matrix.qza

  #Calculate differential analysis scores for exchange reactions

  qiime metnet differentialExchanges \
	--i-reactions ${CURRENT_DIR}/Metnet/output_reactions.qza \
	--m-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
	--m-metadata-column metadataCol \
	--p-condition-name conditionGroup \
	--p-control-name controlGroup \
	--p-selection-model ${pipelineSelection} \
	--p-input-interest inputInterest \
	--o-differential-analysis ${CURRENT_DIR}/Metnet/exchanges_differential.qza

 # Calculate differential analysis scores for any kind of reactions
  qiime metnet differentialReactions \
	--i-reactions ${CURRENT_DIR}/Metnet/output_reactions.qza \
	--m-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
	--m-metadata-column metadataCol \
	--p-condition-name conditionGroup \
	--p-control-name controlGroup \
	--p-selection-model ${pipelineSelection} \
	--o-differential-analysis ${CURRENT_DIR}/Metnet/reactions_differential.qza

# Calculate differential analysis scores for subsystems
  qiime metnet differentialSubSystems \
	--i-reactions ${CURRENT_DIR}/Metnet/output_subsystems.qza \
	--m-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
	--m-metadata-column metadataCol \
	--p-condition-name conditionGroup \
	--p-control-name controlGroup \
	--p-selection-model ${pipelineSelection} \
	--o-differential-analysis ${CURRENT_DIR}/Metnet/subsystems_differential.qza

#Generate the hierarchically-clustered heatmap
qiime metnet plotClusteMap \
	--i-table ${CURRENT_DIR}/Metnet/output_reactions.qza \
	--m-sample-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
	--m-sample-metadata-column metadataCol \
	--o-visualization ${CURRENT_DIR}/Metnet/clustermap.qzv

# Compute and visualize the Principal Component Analysis
qiime metnet plotPCA \
	--i-table ${CURRENT_DIR}/Metnet/output_reactions.qza \
	--m-sample-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
	--m-sample-metadata-column metadataCol \
	--o-visualization ${CURRENT_DIR}/Metnet/pca.qzv











# The parameter --p-namefeature represents the name of the exchange, 
# reaction or subsystem for which we generate the boxplot. The name must be 
# extracted exactly from the differential activity table. It is possible to define a title.


# # Generate the boxplots
# qiime metnet plotBoxplot \
# 	--i-table ${CURRENT_DIR}/metnet/output_reactions.qza \
# 	--i-differentialresults ${CURRENT_DIR}/metnet/exchanges_differential.qza \
# 	--m-sample-metadata-file ${CURRENT_DIR}/samples-metadata.tsv \
# 	--m-sample-metadata-column metadataCol \
# 	--p-condition-name conditionGroup \
# 	--p-control-name controlGroup \
# 	--p-namefeature 'nameExchange' \
# 	--o-visualization ${CURRENT_DIR}/metnet/boxplot.qzv


