#!/bin/bash
set -euo pipefail

source ../../initialize_parameters.sh
#source initialize_parameters.sh

EXPERIMENT_DIR=$PWD
source ${EXPERIMENT_DIR}/config.env

MetnetPerform() {
    local asv_table=$1
    local taxa_table=$2
    local file_name=$3
    local pipelineSelection="AGREDA" # Default is chosen.

    #file_name=$(basename "${taxa_table%.qza}")

    echo "Taxonomy Table: $taxa_table"
    echo "Feature Table: $asv_table"
    echo "${file_name}"
    echo -e "${PURPLE} Metnet running: generating features.. ${NC}"

    mkdir -p "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}"

    #Generate the normalized scores tables
    qiime metnet generateFeatures \
      --i-frequency "$asv_table" \
      --i-taxa "$taxa_table" \
      --p-selection "$pipelineSelection" \
      --p-level "$taxLevel" \
      --o-reactions "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --o-subsystems "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_scores.qza" \
      --o-xmatrix "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/Xmatrix.qza"

    sample_metadata_file="${EXPERIMENT_DIR}/samples-metadata.tsv"

    qiime tools export \
      --input-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --output-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_rxns_scores"

    biom convert \
      -i "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_rxns_scores/feature-table.biom" \
      -o "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_rxns_scores.tsv" \
      --to-tsv

    #Calculate differential analysis scores for exchange reactions
    qiime metnet differentialExchanges \
      --i-reactions "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --m-metadata-file "$sample_metadata_file" \
      --m-metadata-column "$metadataCol" \
      --p-condition-name "$conditionGroup" \
      --p-control-name "$controlGroup" \
      --p-selection-model "$pipelineSelection" \
      --p-input-interest True \
      --o-differential-analysis "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exchanges_rxns_differential.qza"

    qiime tools export \
      --input-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exchanges_rxns_differential.qza" \
      --output-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_exch_rxns"

    biom convert \
      -i "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_exch_rxns/feature-table.biom" \
      -o "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/table_exch_rxns.tsv" \
      --to-tsv

    #Calculate differential analysis scores for any kind of reactions
    qiime metnet differentialReactions \
      --i-reactions "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --m-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-metadata-column "$metadataCol" \
      --p-condition-name "$conditionGroup" \
      --p-control-name "$controlGroup" \
      --p-selection-model "$pipelineSelection" \
      --o-differential-analysis "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_differential.qza"

    qiime tools export \
      --input-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_differential.qza" \
      --output-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_rxns"

    biom convert \
      -i "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_rxns/feature-table.biom" \
      -o "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/table_rxns.tsv" \
      --to-tsv

    #Calculate differential analysis scores for subsystems
    qiime metnet differentialSubSystems \
      --i-subsystems "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_scores.qza" \
      --m-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-metadata-column "$metadataCol" \
      --p-condition-name "$conditionGroup" \
      --p-control-name "$controlGroup" \
      --o-differential-analysis "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_differential.qza"

    qiime tools export \
      --input-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_differential.qza" \
      --output-path "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_subs"

    biom convert \
      -i "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/exported_table_subs/feature-table.biom" \
      -o "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/table_subs.tsv" \
      --to-tsv

    #Generate the hierarchically-clustered heatmap
    qiime metnet plotClusteMap \
      --i-table "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --m-sample-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-sample-metadata-column "$metadataCol" \
      --o-visualization "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_clustermap.qzv"
    #qiime tools view "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_clustermap.qzv"

    qiime metnet plotClusteMap \
      --i-table "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_scores.qza" \
      --m-sample-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-sample-metadata-column "$metadataCol" \
      --o-visualization "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_clustermap.qzv"
    #qiime tools view "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_clustermap.qzv"

    qiime metnet plotPCA \
      --i-table "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_scores.qza" \
      --m-sample-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-sample-metadata-column "$metadataCol" \
      --o-visualization "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_pca.qzv"
    #qiime tools view "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/rxns_pca.qzv"

    qiime metnet plotPCA \
      --i-table "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_scores.qza" \
      --m-sample-metadata-file "${EXPERIMENT_DIR}/samples-metadata.tsv" \
      --m-sample-metadata-column "$metadataCol" \
      --o-visualization "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_pca.qzv"
    #qiime tools view "${EXPERIMENT_DIR}/MetnetFunctionalAnalysis/Metnet_${file_name}/subs_pca.qzv"
}

workflowType="$METNET_WORKFLOW_TYPE"
workflowType_regions="$METNET_WORKFLOW_TYPE_REGIONS"
taxLevel="$METNET_TAX_LEVEL"
metadataCol="$METNET_GROUP"
conditionGroup="$METNET_CONDITION_GROUP"
controlGroup="$METNET_CONTROL_GROUP"

if [ $SEQUENCER == "IT" ] && [ $AMPLIFICATION == "Kit" ] && [ $SPLIT_BY_REGION == "No" ]; then
    db_name="silva"
    asv_table=$(find "${EXPERIMENT_DIR}/dada2_output" \
              -maxdepth 1 -type f -name "merged-table-*.qza" | head -n1)
    taxa_table=$(find "${EXPERIMENT_DIR}/taxonomic_analysis" \
                      -maxdepth 1 -type f -name "taxonomy-${db_name}-*.qza" | head -n1)

    MetnetPerform "$asv_table" "$taxa_table" "all_regions"

elif [ $SEQUENCER == "IT" ] && [ $AMPLIFICATION == "Kit" ] && [ $SPLIT_BY_REGION == "Yes" ]; then
    # Convert REGIONS into an array
    db_name="silva"
    IFS=',' read -r -a regions_array <<< "$V_REGIONS"
    for amplicon in "${regions_array[@]}"; do
              asv_table=$(find "${EXPERIMENT_DIR}/cutprimers_qiime2/${amplicon}/dada2_output" \
                  -maxdepth 1 -type f -name "merged-${amplicon}-table-*.qza" | head -n1)
              taxa_table=$(find "${EXPERIMENT_DIR}/cutprimers_qiime2/${amplicon}/taxonomic_analysis" \
                          -maxdepth 1 -type f -name "${amplicon}-taxonomy-${db_name}-*.qza" | head -n1)

              MetnetPerform "$asv_table" "$taxa_table" "region_${amplicon}"
     done
else
    if [[ $workflowType == "Sidle" ]]; then

        python "$DIR/src/rename_features.py" "${EXPERIMENT_DIR}/sidle/"

        feature_table_renamed="${EXPERIMENT_DIR}/sidle/feature-table-renamed.tsv"
        taxonomy_renamed="${EXPERIMENT_DIR}/sidle/taxonomy-renamed.tsv"

        biom convert \
          -i "$feature_table_renamed" \
          -o "${EXPERIMENT_DIR}/sidle/feature-table-renamed.biom" \
          --to-hdf5 --table-type="OTU table"

        qiime tools import \
          --input-path "${EXPERIMENT_DIR}/sidle/feature-table-renamed.biom" \
          --type 'FeatureTable[Frequency]' \
          --input-format BIOMV210Format \
          --output-path "${EXPERIMENT_DIR}/sidle/feature-table-renamed.qza"

        qiime tools import \
          --input-path "$taxonomy_renamed" \
          --type 'FeatureData[Taxonomy]' \
          --output-path "${EXPERIMENT_DIR}/sidle/taxonomy-renamed.qza"

        asv_table_sidle="${EXPERIMENT_DIR}/sidle/feature-table-renamed.qza"
        taxa_table_sidle="${EXPERIMENT_DIR}/sidle/taxonomy-renamed.qza"

        MetnetPerform "$asv_table_sidle" "$taxa_table_sidle" "sidle"

    elif [[ $workflowType == "Region" ]]; then

        db_name="silva"

        if [[ -z $workflowType_regions ]]; then
            mapfile -t amplicon_array < <(find "$EXPERIMENT_DIR" -maxdepth 1 -type d -name 'V*' -printf '%f\n')
        else
            IFS=',' read -r -a amplicon_array <<< "$workflowType_regions"
        fi
          for amplicon in "${amplicon_array[@]}"; do
              asv_table=$(find "${EXPERIMENT_DIR}/${amplicon}/dada2_output" \
                  -maxdepth 1 -type f -name "merged-${amplicon}-table-*.qza" | head -n1)
              taxa_table=$(find "${EXPERIMENT_DIR}/${amplicon}/taxonomic_analysis" \
                          -maxdepth 1 -type f -name "${amplicon}-taxonomy-${db_name}-*.qza" | head -n1)
                          
              MetnetPerform "$asv_table" "$taxa_table" "region_${amplicon}"
          done
    fi
fi