#!/bin/bash

################___I wanted to use different colors in the terminal for different functions, so I need to initialize them (ref: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)

lightCyan='\033[1;36m'
RED='\033[0;31m'
Purple='\033[0;35m'
White='\033[1;37m'
ORANGE="\033[0;33m"
NC='\033[0m' # No Color

#We store current path:
DIR=$PWD

echo -e "${ORANGE}Please, assure that you have a sample-manifest.tsv file prepared."
echo -e "${Purple}Importing samples.."

##_______2_______Converting .FastQ.gz to Artifacts .qza...
qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-path ${DIR}/samples-manifest.tsv \
  --input-format PairedEndFastqManifestPhred33V2 \
  --output-path ${DIR}/samples.qza
#
# echo -e "${ORANGE} Illumina , unlike IonTorrent, uses two primer, forward and reverse. We need to remove them. ${lightCyan} Please, write the nucleotide sequence of Forward Primer:"
# read forwardPrimer
# echo -e "Now please, write the nucleotide sequence of Reverse Primer:"
# read reversePrimer
#
# echo -e "${Purple} Using cutadapt for removing primers sequences..."
#
#
#
# qiime cutadapt trim-paired \
#     --p-cores 4 \
#     --i-demultiplexed-sequences ${DIR}/samples.qza \
#     --p-front-f ${forwardPrimer} \
#     --p-front-r ${reversePrimer} \
#     --p-match-read-wildcards \
#     --p-match-adapter-wildcards \
#     --p-discard-untrimmed \
#     --o-trimmed-sequences ${DIR}/samples.qza \
#     --quiet




#_______3_______Generating a summary of demultiplexing results... *This fastq.gz files has not been demultiplexed cause each of them correspond to a specific sample. So they dont contain barcodes...
#qiime demux summarize \
#  --i-data  ${DIR}/samples-trimmed.qza \
#  --o-visualization ${DIR}/samples-trimmed.qzv

qiime demux summarize \
  --i-data  ${DIR}/samples.qza \
  --o-visualization ${DIR}/samples.qzv

echo "Samples imported"

echo -e "${ORANGE}Before DADA2 step, you need to visualize demux-paired-end-samples-trimmed.qza (through demux-paired-end-samples-trimmed.qzv) and decide the length of reads, so we can trunc by quality. Take a look to the graph that has been opened up."

qiime tools view ${DIR}/samples.qzv

bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/IL_Primers_Dada2
