#!/bin/bash

################___I wanted to use different colors in the terminal for different functions, so I need to initialize them (ref: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)

lightCyan='\033[1;36m'
RED='\033[0;31m'
Purple='\033[0;35m'
White='\033[1;37m'
ORANGE="\033[0;33m"
NC='\033[0m' # No Color

#We store current path:
DIR=$PWD

#Ask for seq ID numbers
echo -e "Like in IonTorrent, that uses pgm codes for identifying files from different sequentiations, we would use an own code, called Seq. Therefore, you should have your fastqfiles with a SeqX at the beginning (Ex: Seq1_IDEM01-1-G_S13_L001_R1_001.fastq.gz). Remember that you should have prepared a samples-manifest-seqX.tsv for each Seq (being X the number).${lightCyan} Now please, enter the numbers of SEQ sequenciations (ex: 1,2,3):"
read seqNums

#Convert seq numbers to vector
my_string=$seqNums
my_array=($(echo $my_string | tr "," "\n"))

################___We need the truncating and trimming parameters, so we will ask for them:
echo -e "${lightCyan} Enter truncating length for Forward sequences"
read trunc_forward
echo -e "${lightCyan} Enter truncating length for Reverse sequences"
read trunc_reverse
echo -e "${lightCyan} Enter trimming length for Forward sequences"
read trim_forward
echo -e "${lightCyan} Enter trimming length for Reverse sequences"
read trim_reverse

echo -e "${NC}"
#Move to the directory path:
cd ${DIR}

################################### DADA 2 ##############################################
mkdir Dada2_output

 for seqNums in "${my_array[@]}"
  do
####### DADA 2 paired con Trunc Len  ###########

qiime dada2 denoise-paired \
  --i-demultiplexed-seqs ${DIR}/samples-seq${seqNums}.qza \
  --p-trunc-len-f ${trunc_forward} \
  --p-trunc-len-r ${trunc_reverse} \
  --p-trim-left-f ${trim_forward} \
  --p-trim-left-r ${trim_reverse} \
  --p-n-threads 4 \
  --o-representative-sequences ${DIR}/Dada2_output/rep-seqs-paired-seq${seqNums}.qza \
  --o-table ${DIR}/Dada2_output/table-paired-seq${seqNums}.qza \
  --o-denoising-stats ${DIR}/Dada2_output/stats-dada2-paired-seq${seqNums}.qza \
  --verbose


#Visualizing Resulting data...
#Converting DADA2 artifact .qza to .qzv

qiime feature-table summarize \
  --i-table ${DIR}/Dada2_output/table-paired-seq${seqNums}.qza \
  --o-visualization ${DIR}/Dada2_output/table-paired-seq${seqNums}.qzv \
  --m-sample-metadata-file ${DIR}/samples-metadata-seq${seqNums}.tsv
qiime feature-table tabulate-seqs \
  --i-data ${DIR}/Dada2_output/rep-seqs-paired-seq${seqNums}.qza \
  --o-visualization ${DIR}/Dada2_output/rep-seqs-paired-seq${seqNums}.qzv
qiime metadata tabulate \
  --m-input-file ${DIR}/Dada2_output/stats-dada2-paired-seq${seqNums}.qza \
  --o-visualization ${DIR}/Dada2_output/stats-dada2-paired-seq${seqNums}.qzv

     echo "DADA2 performed for $seqNums seq SEQUENCE"
  done


# Create report with the parameters used:
echo -e "${Purple} Creating summary report..."
echo "This is a summary report of the parameters used in DADA2 step: 
                        Truncating Length for Forward sequences: ${trunc_forward}
                        Truncating Length for Reverse sequences: ${trunc_reverse}
                        Trimming Length for Forward sequences: ${trim_forward}
                        Trimming Length for Reverse sequences: ${trim_reverse}" >| ${DIR}/Dada2_output/DADA2_parameters_report.txt



echo -e "${ORANGE}Sometimes the truncating length value we choose may not be optimal. To be able to assess whether we should choose another value, we must view the statistics table that is created after the Dada2 step. To know if the chosen value is good, we must look at the percentage of reads that pass the filter. For example, 70% would not be bad. However, we can re-run the Dada2 step with another value to compare the percentages. Let's visualize the statistic tables of each seq run:${NC}"

for seqNums in "${my_array[@]}"
  do
    qiime tools view ${DIR}/Dada2_output/stats-dada2-paired-seq${seqNums}.qzv
done

echo -e "${ORANGE}Once you have vizualize all the statistic tables... ${lightCyan} Do you want to re-run dada2? (Write Yes or No)"
read repeatDada2

if test ${repeatDada2} == "Yes"
 then 

    bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/IL_Primers_Dada2_different_seqRuns
elif test ${repeatDada2} == "No"
    then
    echo -e "${ORANGE}Now we have run DADA2, we will have 3 files for each seq. In order to continue with the taxonomic analysis, we need to merge table and rep-seqs files."
    echo "Please, edit manually the 'mergeEdit' file that you will find in ./Steps_and_Scripts/3_Qiime2_Pipelines/src folder.${lightCyan} Once you have already modified it, please write Yes:"
    read mergeDone

    if test ${mergeDone} == "Yes"
        then 
        #nano /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/mergeEdit

        bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/mergeEdit
    fi

echo -e "${ORANGE} Make sure the rep-seqs-merged.qza and the table-merged.qza files have been created. Now we will perform the Taxonomic analysis:"

bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/TaxonomicClassification
fi






