#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

#Ask for run ID numbers
echo -e "${LIGHTCYAN}Enter the numbers of run sequencings again (ex: 1,2,3):"
read runNums
array_runs=($(echo $runNums | tr "," "\n"))

echo -e "${ORANGE}Sometimes, different amplicons are mixed in the sample sample, so more than one pair of primers need to be removed. ${LIGHTCYAN}Please, write the number of amplicons:"
read ampliconNumber 

mkdir -p ${EXPERIMENT_PATH}/cutadapt
for i in $(seq 1 $ampliconNumber); do
  echo -e "${LIGHTCYAN}Please, give a name to the amplicon number $i (ex: amp1 / V4):"
  read amplicon_name    
  echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of FORWARD Primer for amplicon $amplicon_name:"
  read fwd_primer
  echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of REVERSE Primer for amplicon $amplicon_name:"
  read rev_primer 
  
  for run in "${array_runs[@]}"; do
    echo -e "${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon_name..."
    qiime cutadapt trim-paired \
      --p-cores 4 \
      --i-demultiplexed-sequences ${EXPERIMENT_PATH}/samples-run${run}.qza \
      --p-front-f ${fwd_primer} \
      --p-front-r ${rev_primer} \
      --p-error-rate 0.1 \
      --p-match-read-wildcards \
      --p-match-adapter-wildcards \
      --p-discard-untrimmed \
      --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon_name}-trimmed.qza \
      --quiet

    # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \
    qiime demux summarize \
      --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon_name}-trimmed.qza \
      --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon_name}-trimmed.qzv

  done
done

# # Create report with the parameters used:
# echo -e "${PURPLE} Creating summary report..."
# echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
#                         Cutadapt yes or no: ${cutadapt}
#                         Forward Primer nucleotide sequence: ${forwardPrimer}
#                         Reverse Primer nucleotide sequence: ${reversePrimer}" >| ${CURRENT_DIR}/Import_trimming_parameters_report.txt


# Perform Dada2
bash $DIR/src/IL_Primers_Dada2
