#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

source ${EXPERIMENT_PATH}/config.env

# Convert AMPLICONS into an array
IFS=',' read -r -a amplicon_array <<< "$AMPLICONS"

mkdir -p ${EXPERIMENT_PATH}/cutadapt

for amplicon in "${amplicon_array[@]}"; do
  # Read amplicon primers:
  fwd_primer_var="${amplicon}_fwd_primer"
  rev_primer_var="${amplicon}_rev_primer"
  fwd_primer="${!fwd_primer_var}"
  rev_primer="${!rev_primer_var}"

  #for run in "${array_runs[@]}"; do
  for run in $(seq 1 $SEQUENCING_RUNS); do
    echo -e "\n${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon..."
    qiime cutadapt trim-paired \
      --p-cores 4 \
      --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
      --p-front-f ${fwd_primer} \
      --p-front-r ${rev_primer} \
      --p-error-rate 0.1 \
      --p-match-read-wildcards \
      --p-match-adapter-wildcards \
      --p-discard-untrimmed \
      --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza \
      --quiet

    # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \
    qiime demux summarize \
      --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza \
      --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qzv

  done
done

# # Create report with the parameters used:
# echo -e "\n${PURPLE} Creating summary report..."
# echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
#                         Cutadapt yes or no: ${cutadapt}
#                         Forward Primer nucleotide sequence: ${forwardPrimer}
#                         Reverse Primer nucleotide sequence: ${reversePrimer}" >| ${CURRENT_DIR}/Import_trimming_parameters_report.txt

echo -e "\n${PURPLE}CUTADAPT PERFORMED!"
# Perform Dada2
bash $DIR/src/IL_Primers_Dada2
