#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

# #Ask for run ID numbers
# echo -e "${LIGHTCYAN}Enter the numbers of run sequencings again (ex: 1,2,3):"
# read runNums
# array_runs=($(echo $runNums | tr "," "\n"))

source ${EXPERIMENT_PATH}/config.env

# echo -e "${ORANGE}Sometimes, different amplicons are mixed in the sample sample, so more than one pair of primers need to be removed. ${LIGHTCYAN}Please, write the number of amplicons:"
# read ampliconNumber 

# Convert AMPLICONS into an array
IFS=',' read -r -a amplicon_array <<< "$AMPLICONS"

mkdir -p ${EXPERIMENT_PATH}/cutadapt
#for i in $(seq 1 $ampliconNumber); do
for amplicon in "${amplicon_array[@]}"; do
  # echo -e "${LIGHTCYAN}Please, give a name to the amplicon number $i (ex: amp1 / V4):"
  # read amplicon_name    
  # echo -e "\n${LIGHTCYAN}Please, write the nucleotide sequence of FORWARD Primer for amplicon $amplicon_name:"
  # read fwd_primer
  # echo -e "\n${LIGHTCYAN}Please, write the nucleotide sequence of REVERSE Primer for amplicon $amplicon_name:"
  # read rev_primer 
  
  # Read amplicon primers:
  fwd_primer_var="${amplicon}_fwd_primer"
  rev_primer_var="${amplicon}_rev_primer"
  fwd_primer="${!fwd_primer_var}"
  rev_primer="${!rev_primer_var}"

  #for run in "${array_runs[@]}"; do
  for run in $(seq 1 $SEQUENCING_RUNS); do
    echo -e "\n${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon_name..."
    qiime cutadapt trim-paired \
      --p-cores 4 \
      --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
      --p-front-f ${fwd_primer} \
      --p-front-r ${rev_primer} \
      --p-error-rate 0.1 \
      --p-match-read-wildcards \
      --p-match-adapter-wildcards \
      --p-discard-untrimmed \
      --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza \
      --quiet

    # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \
    qiime demux summarize \
      --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza \
      --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qzv

  done
done

# # Create report with the parameters used:
# echo -e "\n${PURPLE} Creating summary report..."
# echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
#                         Cutadapt yes or no: ${cutadapt}
#                         Forward Primer nucleotide sequence: ${forwardPrimer}
#                         Reverse Primer nucleotide sequence: ${reversePrimer}" >| ${CURRENT_DIR}/Import_trimming_parameters_report.txt

echo -e "\n${PURPLE}CUTADAPT PERFORMED!"
# Perform Dada2
bash $DIR/src/IL_Primers_Dada2
