#!/bin/bash

source ../../initialize_parameters.sh

# Store current path:
CURRENT_DIR=$PWD

echo -e "${ORANGE}Since you have performed the sequencing with commercial primers, 
you now have two options for removing the sequences: 
(1) If you already know the nucleotide sequence of the primers, we can remove those sequences usign Cutadapt.
(2) If we don't know the specific sequence, we can also use the trimming function of Dada2 for removing the first part of the graph.
The first option is more specific, but both of them can be done.
In this context, ${LIGHTCYAN} do you want to perform Cutadapt (you know the forward and reverse primer nucleotide sequences)? (Write Yes or No)"
read cutadapt

# Apply cutadapt
if test ${cutadapt} == "Yes"; then
  echo -e "${ORANGE}Since the sequencing has been performed using IonTorrent sequencer, 
  no paired sequencing has been done, so only the Forward primer will be removed: "
  # Reference for this decision: https://forum.qiime2.org/t/cutadapt-in-ion-torrent-sequences/22165/9
  
  echo -e "${ORANGE}When analyzing ITS, it is probable that 2 primers have been used for sequencing more than one gene (ITS1 and ITS2, for example).
  If this is your case, you would need to provide 2 primer sequences."

  echo -e "${LIGHTCYAN} Please, write the 1 or 2, depending on how many primers you would like to remove:"
  read num_primers

  if test ${num_primers} == "1"; then
    echo -e "${LIGHTCYAN} Please, write the nucleotide sequence of Forward Primer:"
    read forwardPrimer

    echo -e "${PURPLE} Using cutadapt for removing primer sequences..."
    qiime cutadapt trim-single \
      --p-cores 4 \
      --i-demultiplexed-sequences ${CURRENT_DIR}/samples.qza \
      --p-front ${forwardPrimer} \
      --p-match-read-wildcards \
      --p-match-adapter-wildcards \
      --p-discard-untrimmed \
      --o-trimmed-sequences ${CURRENT_DIR}/samples.qza \
      --quiet

    # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \  
      
    # Create report with the parameters used:
    echo -e "${PURPLE} Creating summary report..."
    echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
                            Cutadapt yes or no: ${cutadapt}
                            Num (#) of primers to trim: ${num_primers}
                            Primer nucleotide sequence: ${forwardPrimer}" >| ${CURRENT_DIR}/Import_trimming_parameters_report.txt

  elif test ${num_primers} == "2"; then
    echo -e "${LIGHTCYAN} Please, write the nucleotide sequence of the first Forward Primer:"
    read forwardPrimer1
    echo -e "${LIGHTCYAN} Please, write the nucleotide sequence of the second Forward Primer:"
    read forwardPrimer2

    echo -e "${PURPLE} Using cutadapt for removing primer sequences..."
    qiime cutadapt trim-single \
      --p-cores 4 \
      --i-demultiplexed-sequences ${CURRENT_DIR}/samples.qza \
      --p-front ${forwardPrimer1} \
      --p-front ${forwardPrimer2} \
      --p-match-read-wildcards \
      --p-match-adapter-wildcards \
      --p-discard-untrimmed \
      --o-trimmed-sequences ${CURRENT_DIR}/samples.qza \
      --quiet

    # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \

    # Create report with the parameters used:
    echo -e "${PURPLE} Creating summary report..."
    echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
                            Cutadapt yes or no: ${cutadapt}
                            Num (#) of primers to trim: ${num_primers}
                            Primer nucleotide sequence (1): ${forwardPrimer1}
                            Primer nucleotide sequence (2): ${forwardPrimer2}" >| ${CURRENT_DIR}/Import_trimming_parameters_report.txt
  fi
fi

qiime demux summarize \
  --i-data  ${CURRENT_DIR}/samples.qza \
  --o-visualization ${CURRENT_DIR}/samples.qzv

# Perform Dada2
bash $DIR/src/IT_Primers_Dada2