#!/bin/bash

source ../../initialize_parameters.sh

# Store current path:
CURRENT_DIR=$PWD

# Ask for run ID numbers
echo -e "${LIGHTCYAN}Now please, enter the numbers of run sequencings (ex: 1,2,3):"
        read runNums

# Convert run numbers to vector
my_string=$runNums
my_array=($(echo $my_string | tr "," "\n"))

# Importing samples to Qiime2
for runNums in "${my_array[@]}"; do
    echo -e "${PURPLE}Importing samples from run $runNums to Qiime2..."
    qiime tools import \
    --type 'SampleData[SequencesWithQuality]' \
    --input-path ${CURRENT_DIR}/samples-manifest-run${runNums}.tsv \
    --input-format SingleEndFastqManifestPhred33V2 \
    --output-path ${CURRENT_DIR}/samples-run${runNums}.qza

    echo -e "${PURPLE}Creating visualization for run $runNums..."
    qiime demux summarize \
      --i-data  ${CURRENT_DIR}/samples-run${runNums}.qza \
      --o-visualization ${CURRENT_DIR}/samples-run${runNums}-demux.qzv
done

echo -e "${ORANGE}Before DADA2 step, you need to visualize samples.qza (through samples-demux.qzv) and decide the length of reads, so we can trunc by quality. When we work with more than one run, we need to decide the truncating length based on all the .qzv samples created. Take a look to all the graphs (one for each run) that have been opened up. (You will need to quit the viewer, pressing 'q', for the next file to open)"

# Visualize Quality graphs
for runNums in "${my_array[@]}"; do
    echo -e "${PURPLE}Opening run $runNums .qzv visualization...${NC}"
    qiime tools view ${CURRENT_DIR}/samples-run${runNums}-demux.qzv
    done

# Perform Dada2
bash $DIR/src/IT_16Skit_Dada2_different_seqRuns
