#!/bin/bash

################___I wanted to use different colors in the terminal for different functions, so I need to initialize them (ref: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)

lightCyan='\033[1;36m'
RED='\033[0;31m'
Purple='\033[0;35m'
White='\033[1;37m'
ORANGE="\033[0;33m"
NC='\033[0m' # No Color

#We store current path:
DIR=$PWD

#Ask for pgm ID numbers
echo -e "${lightCyan} Now please, enter the numbers of PGM sequenciations (ex: 181,182,201):"
        read pgmNums

echo -e "${lightCyan} And the primers sequence that you have used for the PCR: Primer1"
        read primer1
#echo -e "${lightCyan} And the primers sequence that you have used for the PCR: Primer2"
#        read primer2

#Convert pgm numbers to vector
my_string=$pgmNums
my_array=($(echo $my_string | tr "," "\n"))

 for pgmNums in "${my_array[@]}"
  do
    ##_______2_______Converting .FastQ.gz to Artifacts .qza...
    qiime tools import \
    --type 'SampleData[SequencesWithQuality]' \
    --input-path ${DIR}/samples-manifest-pgm${pgmNums}.tsv \
    --input-format SingleEndFastqManifestPhred33V2 \
    --output-path ${DIR}/samples-pgm${pgmNums}.qza

    qiime cutadapt trim-single \
     --p-cores 4 \
     --i-demultiplexed-sequences ${DIR}/samples-pgm${pgmNums}.qza \
     --p-anywhere ${primer1} \
     --p-match-read-wildcards \
     --p-match-adapter-wildcards \
     --p-discard-untrimmed \
     --o-trimmed-sequences ${DIR}/samples-pgm${pgmNums}-trimmed.qza \
     --quiet

    #####recomiendan https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
    #  --p-match-read-wildcards \
    #  --p-match-adapter-wildcards \
    #  --p-discard-untrimmed \

    ##_______3_______Generating a summary of demultiplexing results... *This fastq.gz files has not been demultiplexed cause each of them correspond to a specific sample. So they dont contain barcodes... 
    qiime demux summarize \
      --i-data  ${DIR}/samples-pgm${pgmNums}-trimmed.qza \
      --o-visualization ${DIR}/samples-pgm${pgmNums}-trimmed-demux.qzv

    #qiime tools view ${DIR}/samples-pgm${pgmNums}-demux.qzv

     echo "Welcome $pgmNums PGM SEQUENCE"
  done

echo -e "${ORANGE}Before DADA2 step, you need to visualize samples.qza (through samples-demux.qzv) and decide the length of reads, so we can trunc by quality. When we work with more than one pgm, we need to decide the truncating length based on all the .qzv samples created. Take a look to all the graphs (one for each pgm) that have been opened up. (You will need to quit the viewer for the next file to open)"

for pgmNums in "${my_array[@]}"
do
    qiime tools view ${DIR}/samples-pgm${pgmNums}-trimmed-demux.qzv
done

bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/IT_Primers_Dada2_different_seqRuns
