#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD
SCRIPTS_PATH=${DIR}/src

# my_regions=$V_REGIONS
# array_regions=($(echo $my_regions | tr "," "\n"))

source ${EXPERIMENT_PATH}/config.env

# Convert REGIONS into an array
IFS=',' read -r -a regions_array <<< "$V_REGIONS"

for Vregion in "${regions_array[@]}"; do

    #Create metadata file for regions:
    python3 ${SCRIPTS_PATH}/write_metadata_file.py ${EXPERIMENT_PATH} $Vregion

    #for Vregion in "${array_regions[@]}"; do
    DADA2_PATH=$EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/dada2_output
    # Merge table.qza files:
    input_files_table=()
    trunc_lengths=()
    for file in "$DADA2_PATH"/*-table-*.qza; do
        input_files_table+=("--i-tables $file")
        # Save used trunc_length
        if [[ $file =~ ([0-9]+)\.qza$ ]]; then
            trunc_length="${BASH_REMATCH[1]}"
            trunc_lengths+=("$trunc_length")
        fi
    done

    first_trunc_length="${trunc_lengths[0]}"
    
    echo -e "${PURPLE}Running Taxonomic classification of ${VRegion} with GreenGenesDB vsearch classifier..${NC} "
    mkdir $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis
    ### Greengenes
    qiime feature-classifier classify-consensus-vsearch \
        --i-query $DADA2_PATH/merged-${Vregion}-rep-seqs-pyro-trun${first_trunc_length}.qza  \
        --i-reference-reads $DIR/DATABASES/GreenGenes_DB/gg_13_8_otus/99_otus_refs.qza \
        --i-reference-taxonomy $DIR/DATABASES/GreenGenes_DB/gg_13_8_otus/99_otu_taxonomy.qza \
        --p-strand 'both' \
        --p-threads 4 \
        --o-classification $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-search-results $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-search-results-gg99-vsearch-dada2trun${first_trunc_length}.qza

    qiime metadata tabulate \
        --m-input-file $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-visualization $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qzv
    
    qiime taxa barplot \
        --i-table $DADA2_PATH/merged-${Vregion}-table-pyro-trun${first_trunc_length}.qza \
        --i-taxonomy $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --m-metadata-file $EXPERIMENT_PATH/samples-metadata-${Vregion}.tsv \
        --o-visualization $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/taxaBarplot-${Vregion}-gg99-vsearch.qzv
        #--m-metadata-file $EXPERIMENT_PATH/samples-metadata.tsv \

    echo -e "${PURPLE}Running Taxonomic classification of ${VRegion} with SILVA DB vsearch classifier..${NC} "
    ### SILVA
    qiime feature-classifier classify-consensus-vsearch \
        --i-query $DADA2_PATH/merged-${Vregion}-rep-seqs-pyro-trun${first_trunc_length}.qza  \
        --i-reference-reads $DIR_DATABASES/Silva_DB/silva-138-99-seqs.qza \
        --i-reference-taxonomy $DIR_DATABASES/Silva_DB/silva-138-99-tax.qza \
        --p-strand 'both' \
        --p-threads 4 \
        --o-classification $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-search-results $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-search-results-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza

    qiime metadata tabulate \
        --m-input-file $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-visualization $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qzv
    
    qiime taxa barplot \
        --i-table $DADA2_PATH/merged-${Vregion}-table-pyro-trun${first_trunc_length}.qza \
        --i-taxonomy $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/${Vregion}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --m-metadata-file $EXPERIMENT_PATH/samples-metadata-${Vregion}.tsv \
        --o-visualization $EXPERIMENT_PATH/cutprimers_qiime2/${Vregion}/taxonomic_analysis/taxaBarplot-${Vregion}-silva-138-99-vsearch.qzv


done

### AÑADIR UN SUM DE TODAS LAS REGIONES????
echo -e "\n${PURPLE}TAXONOMIC ANALYSIS BY REGION PERFORMED!"