#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

SCRIPTS_PATH=$DIR/src

# echo -e "${LIGHTCYAN}Now please, enter the numbers of run sequencings (ex: 1,2,3):"
#         read runNums

# array_runs=($(echo $runNums | tr "," "\n"))

source ${EXPERIMENT_PATH}/config.env

#mkdir -p ${EXPERIMENT_PATH}/data
# # Splitting each fastq file into different hypervariable regions:
#for run in "${array_runs[@]}"; do
for run in $(seq 1 $SEQUENCING_RUNS); do

    echo -e "${PURPLE}Splitting fastq files from run $run into different V regions...${NC}"

    MANIFEST_FILE=samples-manifest-run${run}.tsv

    python3 ${SCRIPTS_PATH}/prepare_fastqfiles_bymanifest.py ${EXPERIMENT_PATH}/${MANIFEST_FILE} $run ${EXPERIMENT_PATH}/data

    # 1) Convert fastq.gz to fastq so MetagenopicsPP can be used:
    for file in $EXPERIMENT_PATH/data/data_run${run}/*.fastq.gz; do gzip -d "$file"; done

    MANIFEST_FILE_RUN=$EXPERIMENT_PATH/data/manifest_data_run${run}.txt
    # 2) Apply MetagenomicsPP plugin to divide reads by hypervariable region:
    sh $DIR/MetagenomicsPP/mgpp.sh -m $MANIFEST_FILE_RUN -o $EXPERIMENT_PATH/cutprimers_output_manifest_run${run}

    # 3) Reorganize samples in folders by Vregion:
    #chmod +x $SCRIPTS_PATH/reorganize_samples_byVregion.py
    python3 $SCRIPTS_PATH/reorganize_samples_byVregion.py $EXPERIMENT_PATH/cutprimers_output_manifest_run${run} $EXPERIMENT_PATH/cutprimers_output_sorted_run${run}

    # 4) Write manifest files for reorganized files:
    python3 $SCRIPTS_PATH/write_manifest_file.py $EXPERIMENT_PATH/cutprimers_output_sorted_run${run} ""

    # 5) Remove non necessary folders: 
    rm -r $EXPERIMENT_PATH/cutprimers_output_manifest_run${run}
done

echo -e "\n${PURPLE}READS REORGANIZED BY VREGION!"

# Remove non necessary folders: 
rm -r $EXPERIMENT_PATH/data

# Import files:
bash $DIR/src/IT_MetagenomicsKit_Import