#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

source ${EXPERIMENT_PATH}/config.env

# Decide taxonomic classification
if test ${TAXA_ANALYSIS} == "byregion"; then
    echo -e "${PURPLE}Continuing with by V region classification..."
    bash $DIR/src/IT_MetagenomicsKit_byRegion_tax_classification

elif test ${TAXA_ANALYSIS} == "sidle"; then
    echo -e "${PURPLE}Continuing with Sidle reconstruction..."
    bash $DIR/src/IT_MetagenomicsKit_Sidle_reconstruction

elif test ${TAXA_ANALYSIS} == "both"; then
    echo -e "${PURPLE}Continuing with by V region classification..."
    bash $DIR/src/IT_MetagenomicsKit_byRegion_tax_classification
    echo -e "${PURPLE}Continuing with Sidle reconstruction..."
    bash $DIR/src/IT_MetagenomicsKit_Sidle_reconstruction
fi

# Perform Abundance table analysis
bash $DIR/src/AbundanceTable_analysis_MetagenomicsKit