#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD


source ${EXPERIMENT_PATH}/config.env


mkdir -p ${EXPERIMENT_PATH}/cutadapt

# Convert AMPLICONS into an array
IFS=',' read -r -a amplicon_array <<< "$AMPLICONS"


for amplicon in "${amplicon_array[@]}"; do
  # Read amplicon primers:
  fwd_primer_var="${amplicon}_fwd_primer"
  rev_primer_var="${amplicon}_rev_primer"
  fwd_primer="${!fwd_primer_var}"
  rev_primer="${!rev_primer_var}"

  # # Based on 10.1371/journal.pone.0280293, even if IT is not paired, Forward and reverse sequences are spliited in cutadapt:


  # for run in $(seq 1 $SEQUENCING_RUNS); do
  #     # Perform Cutadapt for Forward reads
  #     echo -e "\n${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon..."
  #     qiime cutadapt trim-single \
  #           --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
  #           --p-front "^${fwd_primer}" \
  #           --p-error-rate 0.1 \
  #           --p-indels \
  #           --p-match-read-wildcards \
  #           --p-match-adapter-wildcards \
  #           --p-discard-untrimmed \
  #           --p-cores 4 \
  #           --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qza \
      
  #     qiime demux summarize \
  #       --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qza \
  #       --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qzv

  #     # Perform Cutadapt for Reverse reads
  #     qiime cutadapt trim-single \
  #           --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
  #           --p-front "^${rev_primer}" \
  #           --p-error-rate 0.1 \
  #           --p-indels \
  #           --p-match-read-wildcards \
  #           --p-match-adapter-wildcards \
  #           --p-discard-untrimmed \
  #           --p-cores 4 \
  #           --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qza \
      
  #     qiime demux summarize \
  #       --i-data ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qza \
  #       --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qzv

  #     # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
  #     #  --p-match-read-wildcards \
  #     #  --p-match-adapter-wildcards \
  #     #  --p-discard-untrimmed \
      

  # Not sure if doing it with fwd and rev is the correct way. Removing the fwd primer as front and rev primer as adapter could be the best. 
  for run in $(seq 1 $SEQUENCING_RUNS); do
      # Perform Cutadapt for Forward reads
      echo -e "\n${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon..."
      qiime cutadapt trim-single \
        --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
        --p-front "^${fwd_primer}" \
        --p-adapter "${rev_primer}" \
        --p-error-rate 0.1 \
        --p-indels \
        --p-match-read-wildcards \
        --p-match-adapter-wildcards \
        --p-discard-untrimmed \
        --p-cores 4 \
        --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza

      qiime demux summarize \
        --i-data ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qza \
        --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-${amplicon}-trimmed.qzv

  done
done

echo -e "\n${PURPLE}CUTADAPT PERFORMED!"
# Perform Dada2
bash $DIR/src/IT_Primers_Dada2