#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

#Ask for run ID numbers
echo -e "${LIGHTCYAN}Enter the numbers of run sequencings again (ex: 1,2,3):"
read runNums
array_runs=($(echo $runNums | tr "," "\n"))

# Based on 10.1371/journal.pone.0280293, even if IT is not paired, Forward and reverse sequences are spliited in cutadapt:
echo -e "${ORANGE}Sometimes, just as for the MetagenomicsKit, different amplicons are mixed in the sample sample, so more than one pair of primers need to be removed. ${LIGHTCYAN}Please, write the number of amplicons:"
read ampliconNumber 

mkdir -p ${EXPERIMENT_PATH}/cutadapt
for i in $(seq 1 $ampliconNumber); do

  echo -e "${LIGHTCYAN}Please, give a name to the amplicon number $i (ex: amp1 / V4):"
  read amplicon_name    
  echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of FORWARD Primer for amplicon $amplicon_name:"
  read fwd_primer
  echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of REVERSE Primer for amplicon $amplicon_name:"
  read rev_primer 

  for run in "${array_runs[@]}"; do
      # Perform Cutadapt for Forward reads
      echo -e "${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon_name..."
      qiime cutadapt trim-single \
            --i-demultiplexed-sequences ${EXPERIMENT_PATH}/samples-run${run}.qza \
            --p-front "^${fwd_primer}" \
            --p-error-rate 0.1 \
            --p-indels \
            --p-match-read-wildcards \
            --p-match-adapter-wildcards \
            --p-discard-untrimmed \
            --p-cores 4 \
            --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-fwd-trimmed.qza \
      
      qiime demux summarize \
        --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-fwd-trimmed.qza \
        --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-fwd-trimmed.qzv

      # Perform Cutadapt for Reverse reads
      qiime cutadapt trim-single \
            --i-demultiplexed-sequences ${EXPERIMENT_PATH}/samples-run${run}.qza \
            --p-front "^${rev_primer}" \
            --p-error-rate 0.1 \
            --p-indels \
            --p-match-read-wildcards \
            --p-match-adapter-wildcards \
            --p-discard-untrimmed \
            --p-cores 4 \
            --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-rev-trimmed.qza \
      
      qiime demux summarize \
        --i-data ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-rev-trimmed.qza \
        --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon_name-rev-trimmed.qzv

      # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
      #  --p-match-read-wildcards \
      #  --p-match-adapter-wildcards \
      #  --p-discard-untrimmed \
      
      # # Create report with the parameters used:
      # echo -e "${PURPLE} Creating summary report..."
      # echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
      #                         Cutadapt yes or no: ${cutadapt}
      #                         Num (#) of primers to trim: ${num_primers}
      #                         Primer nucleotide sequence (1): ${forwardPrimer1}
      #                         Primer nucleotide sequence (2): ${forwardPrimer2}" >| ${EXPERIMENT_PATH}/Import_trimming_parameters_report.txt 
  

  
  done
done

# Perform Dada2
bash $DIR/src/IT_Primers_Dada2