#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

# #Ask for run ID numbers
# echo -e "${LIGHTCYAN}Enter the numbers of run sequencings again (ex: 1,2,3):"
# read runNums
# array_runs=($(echo $runNums | tr "," "\n"))


source ${EXPERIMENT_PATH}/config.env


# echo -e "${ORANGE}Sometimes, just as for the MetagenomicsKit, different amplicons are mixed in the sample sample, so more than one pair of primers need to be removed. ${LIGHTCYAN}Please, write the number of amplicons:"
# read ampliconNumber 

# # Calculate how many amplicons are included in samples:
# ampliconNumber=$(echo "$REGIONS" | tr -cd ',' | wc -c)
# ampliconNumber=$((ampliconNumber + 1))

mkdir -p ${EXPERIMENT_PATH}/cutadapt

# Convert AMPLICONS into an array
IFS=',' read -r -a amplicon_array <<< "$AMPLICONS"


for amplicon in "${amplicon_array[@]}"; do
  # Read amplicon primers:
  fwd_primer_var="${amplicon}_fwd_primer"
  rev_primer_var="${amplicon}_rev_primer"
  fwd_primer="${!fwd_primer_var}"
  rev_primer="${!rev_primer_var}"

# for i in $(seq 1 $ampliconNumber); do

  # echo -e "${LIGHTCYAN}Please, give a name to the amplicon number $i (ex: amp1 / V4):"
  # read amplicon_name    
  # echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of FORWARD Primer for amplicon $amplicon_name:"
  # read fwd_primer
  # echo -e "${LIGHTCYAN}Please, write the nucleotide sequence of REVERSE Primer for amplicon $amplicon_name:"
  # read rev_primer 

  # Based on 10.1371/journal.pone.0280293, even if IT is not paired, Forward and reverse sequences are spliited in cutadapt:

  #for run in "${array_runs[@]}"; do
  for run in $(seq 1 $SEQUENCING_RUNS); do
      # Perform Cutadapt for Forward reads
      echo -e "\n${PURPLE}Using cutadapt for removing Forward primer sequences for run ${run} and amplicon $amplicon..."
      qiime cutadapt trim-single \
            --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
            --p-front "^${fwd_primer}" \
            --p-error-rate 0.1 \
            --p-indels \
            --p-match-read-wildcards \
            --p-match-adapter-wildcards \
            --p-discard-untrimmed \
            --p-cores 4 \
            --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qza \
      
      qiime demux summarize \
        --i-data  ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qza \
        --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-fwd-trimmed.qzv

      # Perform Cutadapt for Reverse reads
      qiime cutadapt trim-single \
            --i-demultiplexed-sequences ${EXPERIMENT_PATH}/import/samples-run${run}.qza \
            --p-front "^${rev_primer}" \
            --p-error-rate 0.1 \
            --p-indels \
            --p-match-read-wildcards \
            --p-match-adapter-wildcards \
            --p-discard-untrimmed \
            --p-cores 4 \
            --o-trimmed-sequences ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qza \
      
      qiime demux summarize \
        --i-data ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qza \
        --o-visualization ${EXPERIMENT_PATH}/cutadapt/samples-run${run}-$amplicon-rev-trimmed.qzv

      # Parameters recommended in https://forum.qiime2.org/t/some-questions-about-cutadapt-demux-paired/19223/3
      #  --p-match-read-wildcards \
      #  --p-match-adapter-wildcards \
      #  --p-discard-untrimmed \
      
      # # Create report with the parameters used:
      # echo -e "${PURPLE} Creating summary report..."
      # echo "This is a summary report of the parameters used in Trimming Preprocessing step: 
      #                         Cutadapt yes or no: ${cutadapt}
      #                         Num (#) of primers to trim: ${num_primers}
      #                         Primer nucleotide sequence (1): ${forwardPrimer1}
      #                         Primer nucleotide sequence (2): ${forwardPrimer2}" >| ${EXPERIMENT_PATH}/Import_trimming_parameters_report.txt 
  

  
  done
done

echo -e "\n${PURPLE}CUTADAPT PERFORMED!"
# Perform Dada2
bash $DIR/src/IT_Primers_Dada2