#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

echo -e "${LIGHTCYAN}Now please, enter the numbers of run sequencings (ex: 1,2,3):"
        read runNums

array_runs=($(echo $runNums | tr "," "\n"))

for run in "${array_runs[@]}"; do
    echo -e "${PURPLE}Importing Ion Torrent Primers samples from run $run to Qiime2...${NC}"
    qiime tools import \
    --type 'SampleData[SequencesWithQuality]' \
    --input-path $EXPERIMENT_PATH/samples-manifest-run${run}.tsv \
    --input-format SingleEndFastqManifestPhred33V2 \
    --output-path $EXPERIMENT_PATH/samples-run${run}.qza

    # echo -e "${PURPLE}Creating visualization for run $run...${NC}"
    # qiime demux summarize \
    # --i-data  $EXPERIMENT_PATH/samples-run${run}.qza \
    # --o-visualization $EXPERIMENT_PATH/samples-run${run}-demux.qzv
done


# Perform Cutadapt
bash $DIR/src/IT_Primers_Cutadapt


