#!/bin/bash
#Here write the path to your experiment:
#******************** CHANGE THE PATH OF THE EXPERIMENT **********************
#DIR=$PWD
DIR="/home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Experiments/IDEM"

#******************** CHANGE THE PATHS AND FILE NAMES **********************
# remember to use seq and paired for Illumina and pgm and pyro for Ion Torrent
#********************YOU NEED TO WRITE THIS ROW FOR EACH RUN YOU ARE ANALYZING:********************
#--i-data ${DIR}/Dada2_output/pgm250-rep-seqs-pyro.qza \
# or
#--i-data ${DIR}/Dada2_output/rep-seqs-paired-seq1.qza \


qiime feature-table merge-seqs \
  --i-data ${DIR}/Dada2_output/pgm181-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm182-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm201-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm207-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm243-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm250-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm258-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm261-rep-seqs-pyro.qza \
  --i-data ${DIR}/Dada2_output/pgm265-rep-seqs-pyro.qza \
  --o-merged-data ${DIR}/Dada2_output/rep-seqs-pyro.qza

qiime feature-table tabulate-seqs \
  --i-data ${DIR}/Dada2_output/rep-seqs-pyro.qza \
  --o-visualization ${DIR}/Dada2_output/rep-seqs-pyro.qzv

#********************YOU NEED TO WRITE THIS ROW FOR EACH PGM YOU ARE ANALYZING: (Note now is not --i-data , but, i--tables)********************
#--i-tables ${DIR}/Dada2_output/pgm250-table.qza \
qiime feature-table merge \
  --i-tables ${DIR}/Dada2_output/pgm181-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm182-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm201-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm207-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm243-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm250-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm258-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm261-table-pyro.qza \
  --i-tables ${DIR}/Dada2_output/pgm265-table-pyro.qza \
  --o-merged-table ${DIR}/Dada2_output/table-pyro.qza \
  --p-overlap-method sum

qiime feature-table summarize \
  --i-table ${DIR}/Dada2_output/table-pyro.qza \
  --o-visualization ${DIR}/Dada2_output/table-pyro.qzv \
  --m-sample-metadata-file ${DIR}/samples-metadata.tsv
