#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

source ${EXPERIMENT_PATH}/config.env

prepare_files_to_picrust2(){
  #local amplicon=$1
  local AMPLICON_PATH=$1
  echo -e "${PURPLE}Preparing input files...${NC}"

  mkdir ${AMPLICON_PATH}/picrust2

  #Exporting data to .biom format
  #identify table file: 
  dada2_table_file=$(ls ${AMPLICON_PATH}/dada2_output | grep "^merged.*table.*\.qza$" | grep -v "filtered" | grep -v "sampleIDbyRegion")
  qiime tools export \
    --input-path ${AMPLICON_PATH}/dada2_output/$dada2_table_file \
    --output-path ${AMPLICON_PATH}/picrust2/exported-feature-table
 
  #Creating .fna file..
  #identify rep-seqs file: 
  dada2_repseq_file=$(ls ${AMPLICON_PATH}/dada2_output | grep "^merged.*rep-seqs.*\.qza$" | grep -v "filtered" | grep -v "sampleIDbyRegion")
  qiime tools export \
  --input-path ${AMPLICON_PATH}/dada2_output/$dada2_repseq_file\
  --output-path ${AMPLICON_PATH}/picrust2/exported-fna-fasta-file
}

run_picrust2(){
  local AMPLICON_PATH=$1
  echo -e "${PURPLE}Activating and running Picrust2..."
  source $DIR_CONDA
  conda activate picrust2
  picrust2_pipeline.py -s ${AMPLICON_PATH}/picrust2/exported-fna-fasta-file/dna-sequences.fasta -i ${AMPLICON_PATH}/picrust2/exported-feature-table/feature-table.biom -o ${AMPLICON_PATH}/picrust2/picrust2_out_pipeline -p 4

  echo -e "${LIGHTCYAN}You should be seeing a huge list of numbers and letters (feature IDs actually) above... 
  These are the FeatureIDs that are removed from the analysis due to poor quality alignment, so.. JUST IN CASE, I would copy and paste them in a TXT file :D "
}


if [ $SEQUENCER == "IT" ] && [ $AMPLIFICATION == "Kit" ] && [ $SPLIT_BY_REGION == "Yes" ]; then
  IFS=',' read -r -a regions_array <<< "$V_REGIONS"
  for amplicon in "${regions_array[@]}"; do
    echo -e "${PURPLE}Running Picrust2 Funtional analysis for amplicon $amplicon...${NC}"
    AMPLICON_PATH=$EXPERIMENT_PATH/cutprimers_qiime2/$amplicon
    prepare_files_to_picrust2 "$AMPLICON_PATH"
  done
  for amplicon in "${regions_array[@]}"; do
    AMPLICON_PATH=$EXPERIMENT_PATH/cutprimers_qiime2/$amplicon
    run_picrust2 "$AMPLICON_PATH" 
  done
elif [ $SEQUENCER == "IT" ] && [ $AMPLIFICATION == "Kit" ] && [ $SPLIT_BY_REGION == "No" ]; then
  AMPLICON_PATH=$EXPERIMENT_PATH
  prepare_files_to_picrust2 "$AMPLICON_PATH"
  run_picrust2 "$AMPLICON_PATH" 
else 
  IFS=',' read -r -a amplicon_array <<< "$AMPLICONS"
  for amplicon in "${amplicon_array[@]}"; do
    echo -e "${PURPLE}Running Picrust2 Funtional analysis for amplicon $amplicon...${NC}"
    AMPLICON_PATH=$EXPERIMENT_PATH/$amplicon
    prepare_files_to_picrust2 "$AMPLICON_PATH"
  done
  for amplicon in "${amplicon_array[@]}"; do
    AMPLICON_PATH=$EXPERIMENT_PATH/$amplicon
    run_picrust2 "$AMPLICON_PATH" 
  done
fi






