#!/bin/bash

################___I wanted to use different colors in the terminal for different functions, so I need to initialize them (ref: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux)

lightCyan='\033[1;36m'
RED='\033[0;31m'
Purple='\033[0;35m'
White='\033[1;37m'
ORANGE="\033[0;33m"
NC='\033[0m' # No Color

#We store current path:
DIR=$PWD
#DIR="/home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Experiments/PGM-250-ELAsamples"

#Note that in order to use picrust2, this has to be intalled previously. (If it is already done it will work. But if is not working take into account that it may be because of this not being installed

echo -e "${ORANGE} In orther to create the files for running Picrust2, ${lightCyan} please, enter the exact name of the dada2 output table.qza file: (ex: table-dada2-pyro-conTrun130)"
read table
echo -e "${lightCyan} Now same for rep-seqs file:(ex: rep-seqs-dada2-pyro-conTrun130)"
read repSeqs

echo -e "${ORANGE} Does the table correspond to a specific samples group (ex: MS or HC) or is the general table? ${lightCyan} (Write the group name or total)"
read tableGroup

echo -e "${Purple}Creating Picrust2 files...${NC}"
cd ${DIR}
mkdir Picrust2_${tableGroup}

#source /home/unidad/miniconda3/etc/profile.d/conda.sh # Or path to where your conda is
#                conda activate qiime2-2022.2

#Exporting data to .biom format
qiime tools export \
  --input-path ${DIR}/Dada2_output/${table}.qza \
  --output-path ${DIR}/Picrust2_${tableGroup}/exported-feature-table-${tableGroup}


#Para crear el .fna "mas o meno"
qiime tools export \
--input-path ${DIR}/Dada2_output/${repSeqs}.qza \
--output-path ${DIR}/Picrust2_${tableGroup}/exported-fna-fasta-file-${tableGroup}

echo -e "${Purple}Activating and running Picrust2..."
source /home/unidad/miniconda3/etc/profile.d/conda.sh
conda activate picrust2
picrust2_pipeline.py -s ${DIR}/Picrust2_${tableGroup}/exported-fna-fasta-file-${tableGroup}/dna-sequences.fasta -i ${DIR}/Picrust2_${tableGroup}/exported-feature-table-${tableGroup}/feature-table.biom -o ${DIR}/Picrust2_${tableGroup}/picrust2_out_pipeline_${tableGroup} -p 4

echo -e "${lightCyan}You should be seeing a huge list of numbers and letters (feature IDs actually) above... These are the FeatureIDs that are removed from the analysis due to poor quality alignment, so.. JUST IN CASE, I would copy and paste them in a TXT file :D "
#picrust2_pipeline.py -s dna-sequences-MS.fasta -i feature-table-MS.biom -o picrust2_out_pipeline_MS -p 1
#picrust2_pipeline.py -s dna-sequences-HC.fasta -i feature-table-HC.biom -o picrust2_out_pipeline_HC -p 1

echo -e "${ORANGE}Now you have already run Picrust2 for a specific table... Do you want to re-run the algorithm for another table? ${lightCyan} (Write Yes or No):"
read repeatPicrust

if test ${repeatPicrust} == "Yes"
then 
bash /home/unidad/Escritorio/MiriamGorostidi/aMICROBIOTA/ANALISYS/Steps_and_Scripts/3_Qiime2_Pipelines/src/PICRUSTpipeline
else
fi


