#!/bin/bash

source ../../initialize_parameters.sh

EXPERIMENT_PATH=$PWD

echo -e "${LIGHTCYAN}Please, enter again the amplicon name(s) used (ex: V3 / amp1 / V3,V4)"
read ampliconNames
array_amplicons=($(echo $ampliconNames | tr "," "\n"))


for amplicon in "${array_amplicons[@]}"; do
    #for amplicon in "${array_regions[@]}"; do
    DADA2_PATH=$EXPERIMENT_PATH/${amplicon}/dada2_output
    # Merge table.qza files:
    input_files_table=()
    trunc_lengths=()
    for file in "$DADA2_PATH"/*-table-*.qza; do
        input_files_table+=("--i-tables $file")
        # Save used trunc_length
        if [[ $file =~ ([0-9]+)\.qza$ ]]; then
            trunc_length="${BASH_REMATCH[1]}"
            trunc_lengths+=("$trunc_length")
        fi
        # Save sequencing type:
        if [[ $file =~ ([^-]+)-trun[0-9]+\.qza$ ]]; then
            seq_type="${BASH_REMATCH[1]}"
            echo "Detected type: $seq_type"
        fi

    done

    first_trunc_length="${trunc_lengths[0]}"
    
    echo -e "${PURPLE}Running Taxonomic classification with GreenGenesDB vsearch classifier for amplicon $amplicon..${NC} "
    mkdir $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis
    ### Greengenes
    qiime feature-classifier classify-consensus-vsearch \
        --i-query $DADA2_PATH/merged-${amplicon}-rep-seqs-${seq_type}-trun${first_trunc_length}.qza  \
        --i-reference-reads $DIR/DATABASES/GreenGenes_DB/gg_13_8_otus/99_otus_refs.qza \
        --i-reference-taxonomy $DIR/DATABASES/GreenGenes_DB/gg_13_8_otus/99_otu_taxonomy.qza \
        --p-strand 'both' \
        --p-threads 4 \
        --o-classification $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-search-results $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-search-results-gg99-vsearch-dada2trun${first_trunc_length}.qza

    qiime metadata tabulate \
        --m-input-file $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-visualization $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qzv
    
    qiime taxa barplot \
        --i-table $DADA2_PATH/merged-${amplicon}-table-${seq_type}-trun${first_trunc_length}.qza \
        --i-taxonomy $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-gg99-vsearch-dada2trun${first_trunc_length}.qza \
        --m-metadata-file $EXPERIMENT_PATH/samples-metadata.tsv \
        --o-visualization $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/taxaBarplot-${amplicon}-gg99-vsearch.qzv

    echo -e "${PURPLE}Running Taxonomic classification with SILVA DB vsearch classifier..${NC} "
    ### SILVA
    qiime feature-classifier classify-consensus-vsearch \
        --i-query $DADA2_PATH/merged-${amplicon}-rep-seqs-${seq_type}-trun${first_trunc_length}.qza  \
        --i-reference-reads $DIR_DATABASES/Silva_DB/silva-138-99-seqs.qza \
        --i-reference-taxonomy $DIR_DATABASES/Silva_DB/silva-138-99-tax.qza \
        --p-strand 'both' \
        --p-threads 4 \
        --o-classification $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-search-results $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-search-results-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza

    qiime metadata tabulate \
        --m-input-file $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --o-visualization $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qzv
    
    qiime taxa barplot \
        --i-table $DADA2_PATH/merged-${amplicon}-table-${seq_type}-trun${first_trunc_length}.qza \
        --i-taxonomy $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/${amplicon}-taxonomy-silva-138-99-vsearch-dada2trun${first_trunc_length}.qza \
        --m-metadata-file $EXPERIMENT_PATH/samples-metadata.tsv \
        --o-visualization $EXPERIMENT_PATH/${amplicon}/taxonomic_analysis/taxaBarplot-${amplicon}-silva-138-99-vsearch.qzv
done

### AÑADIR UN SUM DE TODAS LAS REGIONES????